banner.location: logo
spring:
  jmx.enabled: false
  output:
    ansi:
      enabled: always
  redis:
    cluster:
      nodes: 10.3.104.33:7000,10.3.104.33:7001,10.3.104.33:7003,10.3.104.33:7005,10.3.104.33:7006,10.3.104.33:7007,10.3.104.33:7009,10.3.104.33:7010,10.3.104.33:7011,10.3.104.33:7012
      timeout: 2000
      max-redirects: 8
server.port: 8081

spring.cache.cache-names: info,nodes
spring.cache.guava.spec: maximumSize=100,expireAfterWrite=300s

#logging.level.root: WARN
logging.level.com.acumen: DEBUG

#logging.level.org.springframework: TRACE
